apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-tests
spec:
  params:
    - name: PYTHON
      description: The used Python version, more precisely the tag for the Python image
      type: string
      default: "latest"
    - name: SOURCE_PATH
      description: The path to the source code
      default: "."
    - name: REQUIREMENTS_FILE
      description: The name of the requirements file inside the source location, with fallback to the requirements file in the root location
      default: "requirements.txt"
  workspaces:
    - name: source
  steps:
    - name: unit-test
      image: docker.io/python:$(inputs.params.PYTHON)
      workingDir: $(workspaces.source.path)
      script: |
        export PATH=$PATH:$HOME/.local/bin

        if [ -e "$(inputs.params.SOURCE_PATH)"/"$(inputs.params.REQUIREMENTS_FILE)" ];
        then
          pip install -r "$(inputs.params.SOURCE_PATH)"/"$(inputs.params.REQUIREMENTS_FILE)"
        else
          if [ -e "$(inputs.params.REQUIREMENTS_FILE)" ];
          then
            pip install -r "$(inputs.params.REQUIREMENTS_FILE)"
          fi
        fi
        python "$(inputs.params.SOURCE_PATH)"/manage.py test